name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '8'

      # https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
      - name: Cache .m2
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: 'm2-cache'

      - name: Install
        run: sudo apt-get install xvfb libgtk2.0-0 libxtst6 -y

      - name: Build
        run: xvfb-run mvn -V -B clean verify

      - name: Test
        run: xvfb-run testflowrunner/runTestflows.sh

      - name: Upload Update Site
        # https://stackoverflow.com/questions/58139406/only-run-job-on-specific-branch-with-github-actions
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')
        run: |
          branch=${GITHUB_REF#refs/heads/}
          label=${branch#release/}
          curl -s https://download.nodepit.com/developers/upload-update-site.sh |\
            bash -s -- $SFTP_USER $SFTP_PASSWORD $label
        env:
          SFTP_USER: cyface
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}

      - name: Upload Docs
        # https://stackoverflow.com/questions/58139406/only-run-job-on-specific-branch-with-github-actions
        if: github.ref == 'refs/heads/release/3.6'
        run: |
          curl -s https://download.nodepit.com/developers/update-product.sh |\
            bash -s -- -p PRODUCT.md -c CHANGELOG.md $PRODUCT_ID $PRODUCT_EDIT_TOKEN
        env:
          PRODUCT_ID: cyface
          PRODUCT_EDIT_TOKEN: ${{ secrets.PRODUCT_EDIT_TOKEN }}
