name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '8'

      # https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
      - name: Cache .m2
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: 'm2-cache'

      - name: Install
        run: sudo apt-get install xvfb libgtk2.0-0 libxtst6 -y

      - name: Build
        run: xvfb-run mvn -V -B clean verify

      # - name: Test
      #   run: xvfb-run de.cyface.knime.testflowrunner/runTestflows.sh

      - name: Publish to NodePit
        # https://stackoverflow.com/questions/58139406/only-run-job-on-specific-branch-with-github-actions
        # TODO: Enable next line
        # if: github.ref == 'refs/heads/master'
        # TODO: Change `dest_directory` from "test" to "3.5"
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          dest_directory=/home/debian/nodepit/download/files/cyface/test
          ssh $USER_HOST "mkdir -p $dest_directory"
          scp -rp de.cyface.knime.p2/target/repository/* $USER_HOST:$dest_directory
          scp -p de.cyface.knime.p2/target/de.cyface.knime.p2-*.zip $USER_HOST:$dest_directory.zip
          ./update-product.sh https://nodepit.com/api/product/cyface $PRODUCT_EDIT_TOKEN CHANGELOG.md
        env:
          PRODUCT_EDIT_TOKEN: ${{ secrets.PRODUCT_EDIT_TOKEN }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER_HOST: debian@nodepit.com
